name: Deploy to AWS

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t ghcr.io/2000ghz/hello-2048/hello-2048:latest .
          docker push ghcr.io/2000ghz/hello-2048/hello-2048:latest

      - name: Launch EC2 instance
        run: |
          INSTANCE_ID=$(aws ec2 run-instances \
            --image-id ami-05432c5a0f7b1bfd0 \
            --instance-type t2.micro \
            --security-group-ids sg-0929342213735a16c \
            --subnet-id subnet-0818b9561675ff47e \
            --key-name my-key-pair \
            --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=my-instance}]" \
            --query "Instances[0].InstanceId" \
            --output text)
          aws ec2 wait instance-running --instance-ids $INSTANCE_ID

      - name: Get EC2 instance IP
        id: get-instance-ip
        run: |
          INSTANCE_IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query "Reservations[0].Instances[0].PublicIpAddress" --output text)
          echo "::set-output name=instance-ip::$INSTANCE_IP"

      - name: Copy program to EC2 instance
        run: |
          scp -o StrictHostKeyChecking=no -i ${{ secrets.PRIVATE_KEY }} -r path/to/program ec2-user@${{ steps.get-instance-ip.outputs.instance-ip }}:/path/to/destination

      - name: Run program on EC2 instance
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.PRIVATE_KEY }} ec2-user@${{ steps.get-instance-ip.outputs.instance-ip }} "cd /path/to/destination && ./program.sh"
